/* eslint-disable @next/next/no-img-element */
import Layout from "@/components/layout";
import React from "react";
import Styles from "../../styles/Home.module.css";
import Head from "next/head";
import { titleWeb } from "..";
import useSWR from "swr";
import { titlePage, urlAPI } from "./controller";
import styles from "../../styles/Home.module.css";

export default function Index() {
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error, isLoading } = useSWR(urlAPI, fetcher);

  if (error) return <div className={styles.main}>failed to load</div>;
  if (isLoading) return <div className={styles.main}>loading...</div>;
  return (
    <Layout>
      <Head>
        <title>
          {titlePage} | {titleWeb}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.main}>
        <div className="grid grid-cols-1 gap-4">
          {data.map((e, i) => {
            return (
              <div key={i} className={"w-[300px] text-center"}>
                <h1>{e.name}</h1>
                <div className="w-full h-[200px] overflow-clip rounded-xl">
                  <img
                    className="w-full h-full"
                    src={e.images.picture_url}
                    alt={"#"}
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </Layout>
  );
}
