import Layout from "@/components/layout";
import React from "react";
import Styles from "../styles/Home.module.css";
import Head from "next/head";

const titleWeb = "Belajar Fullstack Developer";
export default function index() {
  return (
    <Layout>
      <Head>
        <title>{titleWeb}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.main}>
        <h1>Febir</h1>
      </div>
    </Layout>
  );
}
export { titleWeb };
