/* eslint-disable @next/next/no-img-element */
import React from "react";
import { useRouter } from "next/router";
import useSWR from "swr";
import Head from "next/head";
import Styles from "../../styles/Home.module.css";

export default function Id() {
  const route = useRouter();
  const { id } = route.query;
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error, isLoading } = useSWR(
    `http://localhost:3000/api/users/${id}`,
    fetcher
  );

  if (error) return <div className={Styles.main}>failed to load</div>;
  if (isLoading) return <div className={Styles.main}>loading...</div>;

  return (
    <div>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.main}>
        <h1>{data.title}</h1>
        <img src={data.poster} alt={"#"} />
      </div>
    </div>
  );
}
